### ISSUE TITLE
Valid UserAgent breaks OpenDDR

### ISSUE THREAD

**Issue by nextdayflight** [OpenDDRdotORG/OpenDDR-Java#5]
Hi, I came across a UserAgent which causes the OpenDDR IdentificationService to break:
Mozilla/5.0 (Linux; U; Android 2.2; en-gb; HTC_Desire-orange-LS Build/FRF91(KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

stacktrace:

java.lang.RuntimeException: java.util.regex.PatternSyntaxException: Unclosed group near index 18
Build/FRF91(KHTML,
                  ^
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 18
Build/FRF91(KHTML,
                  ^
        at org.openddr.simpleapi.oddr.builder.device.AndroidDeviceBuilder.cleanPatternElementInside(AndroidDeviceBuilder.java:230)
        at org.openddr.simpleapi.oddr.builder.device.AndroidDeviceBuilder.elaborateAndroidDeviceWithToken(AndroidDeviceBuilder.java:93)
        at org.openddr.simpleapi.oddr.builder.device.AndroidDeviceBuilder.build(AndroidDeviceBuilder.java:57)
        at org.openddr.simpleapi.oddr.builder.device.AndroidDeviceBuilder.build(AndroidDeviceBuilder.java:33)
        at org.openddr.simpleapi.oddr.identificator.DeviceIdentificator.get(DeviceIdentificator.java:63)
        at org.openddr.simpleapi.oddr.ODDRService.getPropertyValues(ODDRService.java:757)
        at com.hitwise.ongard.core.mobile.DeviceRegistry.classify(DeviceRegistry.java:72)
        ... 2 more

**Comment by OpenDDR** [comment]
Hi nextdayflight,
First of all, thank you for your contribute!
We have analyzed your issue and found the problem. There is an error in BUILD_HASH_REGEXP, We have just committed the fix.

Best regards,
OpenDDR Dev. Team
